class ClassName:
    url = "https://dashboard.stagingvelocity.in/auth/login"
    stagging_signup_url = "https://dashboard.stagingvelocity.in/auth/signup"
    stagging_login_url = "https://dashboard.stagingvelocity.in/auth/login"
    sandbox_signup_url = "https://sandbox-dashboard.stagingvelocity.in/auth/signup"
    textbox_username_Xpath = "//input[@placeholder='Email OR Phone']"
    textbox_password_Xpath = "//input[@placeholder='********']"
    button_login_Xpath = "//span[normalize-space()='SIGN IN']"
    Otp_enter = "//input[@placeholder='123456']"
    conirm_otp = "//span[normalize-space()='CONFIRM']"
    dashboard_xpath = "//h3[normalize-space()='Select the product you want to continue with']"
    choose_xpath = "//span[normalize-space()='CHOOSE']"
    get_started_card_xpath = "//button[@id='b_get_started_product_Card']//span[contains(text(),'GET STARTED')]"
    Sign_to_continue = "//h3[normalize-space()='Sign in to continue']"
    Sign_up_now_x_path = "//a[@id='b_signin_link_to_signup']"
    Email_phone_xpath = "//label[normalize-space()='Enter Email Address OR Phone Number']"
    password_string_xpath = "//label[normalize-space()='Password']"
    remind_me_xpath = "//span[normalize-space()='Remember me']"
    Forgot_password = "//a[@id='b_signin_forgot_password']"
    sign_in_xpath = "//button[@id='b_signin_submit']"
    privacy_policy_xpath = "//a[normalize-space()='Privacy policy']"
    Sign_up_to_continue_xpath = "//h3[normalize-space()='Sign up to continue']"
    your_Name_xpath = "//label[normalize-space()='Your Name']"
    email_address = "//label[normalize-space()='Email Address']"
    phone_no_xpath = "//label[normalize-space()='Phone Number']"
    whatsApp = "//span[normalize-space()='I agree to receive updates on WhatsApp']"
    password_signuppage = "//label[normalize-space()='Password']"
    signup_signup = "//button[@id='b_signup_submit']"
    signup_privacy_policy = "//a[normalize-space()='Privacy policy']"
    signup_sign_in_now = "//a[@id='b_signup_link_to_login']"
    signup_your_name_field = "//input[@placeholder='Elon Musk']"
    signup_mobile_no_field = "//input[@name='phone']"
    signup_password_field = "//input[@placeholder='********']"
    signup_emailAddress_filed = "//input[@placeholder='name@company.com']"
    signup_signup_button = "//span[normalize-space()='SIGN UP']"
    enter_otp_xpath = "//input[@placeholder='123456']"
    get_started_finance_xpath = "//button[@id='b_get_started_product_Finance']"
    clk_confirm_sign_otp_xpath = "//button[@id='b_verifyotp_submit']"
    get_started_payments_xpath = "//button[@id='b_get_started_product_Payments']//span[contains(text(),'GET STARTED')]"
    apply_now_xpath = "//span[normalize-space()='Apply Now']"
    Business_type_xpath = "//div[contains(text(),'Business Type')]"
    company_details_xpath = "//div[contains(text(),'Company Details')]"
    your_company_name_xpath = "//div[@class='ant-row']//div[1]//div[1]//input[1]"
    company_name = " Velocity private limited solution"
    company_email_xpath = "//input[@placeholder='https://velocity.in']"
    company_email = "https://www.velocity.in"
    Apparel_and_Footwear_x_path = "//div[@class='ant-row']//div[1]//div[1]//div[1]//div[1]"
    business_details_xpath = "//div[contains(text(),'Business Details')]"
    finance_details_xpath = "//div[contains(text(),'Finance Details')]"
    Your_Company_Website_xpath = "//input[@placeholder='https://velocity.in']"
    company_web_url = "www.velovity.in"
    your_mobile_no_xpath = "//input[@class='ant-input']"
    your_mobile_no = "6203882300"
    your_email_xpath = "//input[@inputmode='email']"
    your_email = "raghuraj@velocity.in"
    next_xpath = "//span[normalize-space()='NEXT']"
    your_name_xpath = "//div[3]//div[1]//input[1]"
    your_name = "Raghuraj Pratap Singh"
    Enter_otp_xpath = "//input[@type='text']"
    otp = "123456"
    next_otp_xpath = "//span[normalize-space()='NEXT']"
    monthly_avg_online_revenue = "//body[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]"
    gross_margins_of_your_business = "//div[@class='rightContent___3AMU-']//div[2]//div[4]//div[1]//div[3]"
    digital_marketing_every_month = "//body[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[3]/div[4]/div[1]/div[3]"
    slider_next_button_xpath = "//span[normalize-space()='NEXT']"
    current_cash = "//body[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]"
    cash_burn = "//body/div[@id='root']/div/div[@class='otherContainer___POPXx']/div[@class='right___2iy0b']/div[@class='rightContent___3AMU-']/div[@class='containerMain___1Ew4g']/div[@class='left___16P4R']/div[@class='content___6hOWY']/div[@class='questionsContainer___242t2']/div[2]/div[4]/div[1]"
    fund_from_velocity = "//body[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[3]/div[4]/div[1]/div[3]"
    fund_deploy_in_velocity = "//body[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[4]/div[4]/div[1]/div[3]"
    submit_button_xpath = "//button[@class='ant-btn button___200ZM']"
    Application_Submitted = "//p[@class='applicationStatus___3-JXn']"
    Name_is_required = "//p[normalize-space()='Name is required']"
    Email_address_is_required = "//p[normalize-space()='Email Address is required']"
    Phone_no_is_required = "//p[normalize-space()='Phone Number is required']"
    password_is_required = "//p[normalize-space()='Password is required']"


obj = ClassName()
