class ClassName:
    url = "https://dashboard.stagingvelocity.in/auth/login"
    stagging_signup_url = "https://dashboard.stagingvelocity.in/auth/signup"
    textbox_username_Xpath = "//input[@placeholder='Email OR Phone']"
    textbox_password_Xpath = "//input[@placeholder='********']"
    button_login_Xpath = "//span[normalize-space()='SIGN IN']"
    Otp_enter = "//input[@placeholder='123456']"
    conirm_otp = "//span[normalize-space()='CONFIRM']"
    dashboard_xpath = "//h3[normalize-space()='Select the product you want to continue with']"
    choose_xpath = "//span[normalize-space()='CHOOSE']"
    get_started_xpath = "//button[@id='b_get_started_product_Card']//span[contains(text(),'GET STARTED')]"
    Sign_to_continue = "//h3[normalize-space()='Sign in to continue']"
    Sign_up_now_x_path = "//a[@id='b_signin_link_to_signup']"
    Email_phone_xpath = "//label[normalize-space()='Enter Email Address OR Phone Number']"
    password_string_xpath = "//label[normalize-space()='Password']"
    remind_me_xpath = "//span[normalize-space()='Remember me']"
    Forgot_password = "//a[@id='b_signin_forgot_password']"
    sign_in_xpath = "//button[@id='b_signin_submit']"
    privacy_policy_xpath = "//a[normalize-space()='Privacy policy']"
    Sign_up_to_continue_xpath = "//h3[normalize-space()='Sign up to continue']"
    your_Name_xpath = "//label[normalize-space()='Your Name']"
    email_address = "//label[normalize-space()='Email Address']"
    phone_no_xpath = "//label[normalize-space()='Phone Number']"
    whatsApp = "//span[normalize-space()='I agree to receive updates on WhatsApp']"
    password_signuppage = "//label[normalize-space()='Password']"
    signup_signup = "//button[@id='b_signup_submit']"
    signup_privacy_policy = "//a[normalize-space()='Privacy policy']"
    signup_sign_in_now = "//a[@id='b_signup_link_to_login']"
    signup_your_name_field = "//input[@placeholder='Elon Musk']"
    signup_mobile_no_field = "//input[@name='phone']"
    signup_password_field = "//input[@placeholder='********']"
    signup_emailAddress_filed = "//input[@placeholder='name@company.com']"
    signup_signup_button = "//span[normalize-space()='SIGN UP']"
    enter_otp_xpath = "//input[@placeholder='123456']"


obj = ClassName()
